# FROM node:20-alpine

# RUN npm install -g pnpm

# WORKDIR /app

# COPY pnpm-lock.yaml ./

# COPY apps/auth-service/package.json ./apps/auth-service/

# WORKDIR /app/apps/auth-service

# RUN pnpm install

# COPY . /app

# EXPOSE 4001

# CMD [ "pnpm", "run", "start" ]


FROM node:20-alpine
 
WORKDIR /app
 
RUN npm install -g pnpm
ENV CI=true
 
COPY . .
 
RUN pnpm install
 
EXPOSE 4001
 
CMD ["pnpm", "--filter", "auth-service", "dev"]
 
